### PR TITLE
Upgraded reap to solve security issue with reap's dependency ms

### PR DESCRIPTION
**Pull request by kamesh95**
Upgraded reap module to solve ReDoS vulnerability - https://nodesecurity.io/advisories/46 with ms package.
The vulnerability in ms package was patched in versions > 7.0.0 but was not updated in it's dependent reap module. So this pull request solves that security issue with reap by upgrading it to reap2.

### CODE REVIEW

**Comment by pofider** [comment]
Please check the [failing ci](https://travis-ci.org/jsreport/jsreport-core/jobs/326805482) and change the `reap` => `reap2` also in the code. Thank you.

**Comment by bjrmatos** [comment]
@kamesh95 hmm so far [i don't see any dev or dependency listed in the package.json of reap2](https://github.com/kamesh95/reap/blob/master/package.json#L6) is that intended? seems like this would fail in a fresh npm install

**Comment by bjrmatos** [comment]
@kamesh95 just in case, you can see the all the original source files of reap [here](https://unpkg.com/reap@0.1.0/)

**Comment by kamesh95** [comment]
@pofider Oh yes. @bjrmatos Sorry. I just forgot to include it's actual dependencies in the newly created package.json I will fix this

**Comment by kamesh95** [comment]
@pofider @bjrmatos Fixed!

**Comment by pofider** [comment]
Thank you.

**Pull request merged**
